Add attest protobuf
mobilecoinfoundation/protobufs pull request #2
Opened 2023-02-07 00:10 UTC by nick-mobilecoin

2023-02-07 00:10 UTC, nick-mobilecoin commented
Current dependencies on/for this PR:
* main
  * **PR #1** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/probufs/1" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #2** <a href="https://app.graphite.dev/github/pr/mobilecoinfoundation/probufs/2" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/mobilecoinfoundation/probufs/2?utm_source=stack-comment).

2023-02-07 00:21 UTC, nick-mobilecoin commented on .github/workflows/ci.yaml
> +  buf-lint:
buf-breaking doesn't work until we have proto files in the repo :(
So once this lands then I can add the buf-breaking ci check

2023-02-07 00:25 UTC, nick-mobilecoin commented on attestapis/buf.md
> +The APIs required to interact with the `AttestService`.
I'm up for suggestions on these docs.

Also you can see the rendering [here](https://github.com/mobilecoinfoundation/probufs/blob/nick/attest-proto/attestapis/buf.md)

2023-02-07 00:25 UTC, nick-mobilecoin commented on attestapis/buf.yaml
> +name: buf.build/nick-mc/attestapis
we'll need to decide where we publish to.

This PR shouldn't be merged until this is agreed on

2023-02-07 00:26 UTC, jcape requested changes
We should split types and services, I dislike "attestapis" as a name, and also I'd prefer to have the package end up being called `mobilecoinfoundation.attest.v1` or something similar.

2023-02-07 16:48 UTC, nick-mobilecoin commented on attestapis/buf.yaml
> +name: buf.build/nick-mc/attestapis
updated name

2023-02-07 16:51 UTC, nick-mobilecoin commented on foundation/mobilecoinfoundation/attestation/v1/attest.proto
> +// The APIs required to interact with the `AttestService`.
per https://docs.buf.build/bsr/documentation#package-documentation, package documentation goes in the alphabetically first module prior to the package directive

2023-02-07 16:55 UTC, nick-mobilecoin commented on foundation/buf.lock
> +# Generated by buf. DO NOT EDIT.
I believe the `foundation` was the repo/module name that was agreed to go into, https://buf.build/mobilecoin
unless we create a new `mobilecoinfoundation` owner

2023-02-09 18:46 UTC, awygle approved these changes
This matches what we discussed in the meeting.

2023-02-09 18:47 UTC, nick-mobilecoin commented on foundation/buf.lock
> +# Generated by buf. DO NOT EDIT.
resolved we're creating a mobilecoinfoundation owner

2023-02-10 21:53 UTC, jcape approved these changes
LGTM, one comment

2023-02-10 21:53 UTC, jcape commented on mobilecoinfoundation/attestation/v1/attest.proto
> +//     Enclave_1->>+Enclave_2: MutualAttestRequest
```suggestion
//     Enclave_1->>+Enclave_2: MutualAttestRequest
//     Enclave_2->>Enclave_2: Verify MutualAttestRequest contents
```

2023-02-11 00:08 UTC, nick-mobilecoin commented on mobilecoinfoundation/attestation/v1/attest.proto
> +//     Enclave_1->>+Enclave_2: MutualAttestRequest
Updated, also fixed spelling of `Messge` on line 37

2023-02-11 00:11 UTC, merged